### ISSUE TITLE
Installation gets stuck on error and retrying pip install bpycv

### ISSUE THREAD

**Issue by bmiserez** [DIYer22/bpycv#31]
Hi, thanks for the great initiative of creating this package. 

I am having trouble with the installation. I have windows 10, blender 2.82, python 3.7.4, pip 21.3.1. There is no module ensurepip, and I seem to be unable to install it. When I execute `blender -b --python-expr "__import__('pip._internal')._internal.main(['install', '-U', 'bpycv'])"`, the terminal gets in a loop of error and retrying to install. The error output is shown in the added screenshots, with the second screenshot looping.

Any clue on how to solve this?

Thanks!

![ss1](https://user-images.githubusercontent.com/89132742/149553337-00fe65e2-6cbf-4eeb-a285-66539b88d75f.png)
![ss2](https://user-images.githubusercontent.com/89132742/149553340-0f81b8c5-19d1-4f06-a126-9c00fc3b0885.png)

**Comment by jackyzyb** [comment]
Same here on MacOS.

**Comment by DIYer22** [comment]
I have repeated this error on Windows. The solution is:
`/blender-path/2.xx/python/bin/python3.7m -m pip install bpycv`

**Comment by jackyzyb** [comment]
> python3.7m

The problem was addressed when I switched to a Macbook with an intel chip (before was M1). (It's this true that bpycv is not supported on M1?)

Another two weird issues: 
1) bpycv is successfully installed with Blender 2.9.1 version (i.e., failed with2.8.3, 2.8.1, 2.8.0). Haven't checked this is due to my laptop or sth else.
2) when using bpycv + Blender 2.9.1, I cannot set the engine as CYCLES. The error is raised by this line: https://github.com/DIYer22/bpycv/blob/master/bpycv/render_utils.py#L56

**Comment by jackyzyb** [comment]
> The problem was addressed when I switched to a Macbook with an intel chip (before was M1). (It's this true that bpycv is not supported on M1?)
> 
> Another weird issue is that bpycv is successfully installed with Blender 2.9.1 version (i.e., failed with2.8.3, 2.8.1, 2.8.0). Haven't checked this is due to my laptop or sth else.

**Comment by DIYer22** [comment]
Sorry, I don't have a Mac environment to test. Maybe it's better to run bpycv through docker on Mac

**Comment by bmiserez** [comment]
> I have repeated this error on Windows. The solution is: `/blender-path/2.xx/python/bin/python3.7m -m pip install bpycv`

Perfect, this works for me! Thanks a lot
